### Test Signup
POST http://localhost:8080/api/user/signup
Content-Type: application/json

{
  "username": "ranjan",
  "email": "ranjan@gmail.com",
  "password": "1234"
}

### Test Login (valid user)
POST http://localhost:8080/api/user/login
Content-Type: application/json

{
  "email": "ranjan@gmail.com",
  "password": "1234"
}

### Get user by ID
GET http://localhost:8080/api/user/68d9113a3a258403ab4bdbde
Content-Type: application/json
