### Test Signup
POST http://localhost:8080/api/user/signup
Content-Type: application/json

{
  "username": "ripu",
  "email": "ripu@eexample.com",
  "password": "1234"
}

### Test Login (valid user)
POST http://localhost:8080/api/user/login
Content-Type: application/json

{
  "email": "ripu@eexample.com",
  "password": "1234"
}

### Get user by ID
GET http://localhost:8080/api/user/68d8920a1c30d1c1c72b4
Content-Type: application/json
